# Generated by Django 5.0.2 on 2024-02-14 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='empcode',
            field=models.CharField(max_length=3),
        ),
    ]
